package cl.duoc.seguro.vistas;

import cl.duoc.seguro.control.ControlAutomotriz;
import cl.duoc.seguro.control.ControlVida;
import cl.duoc.seguro.dominio.Automotriz;
/////import cl.duoc.seguro.dominio.Vehiculo;
import cl.duoc.seguro.dominio.Vida;
import javax.swing.JOptionPane;

public class MenuUnico extends javax.swing.JFrame {

    public MenuUnico() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIdentificador = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        txtFechaVigencia = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        txtDeducible = new javax.swing.JTextField();
        txtPatente = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtAvaluoFiscal = new javax.swing.JTextField();
        btnEliminarVida = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtNombreAsegurado = new javax.swing.JTextField();
        txtEdadAsegurado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtValorFallecimiento = new javax.swing.JTextField();
        cblSeleccionSeguro = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnEliminarAutomotriz = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtIngresoIDPagar = new javax.swing.JTextField();
        btnPagarSeguroVida = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtMuestraPagoSeguro = new javax.swing.JTextField();
        btnPagarSeguroAuto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu Principal"));
        jPanel1.setName("Menu Principal"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Identificador :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nombre Cliente:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Fecha Vigencia :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Costo :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Patente :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Deducible :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Avaluo Fiscal :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Marca :");

        txtIdentificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificadorActionPerformed(evt);
            }
        });

        txtDeducible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeducibleActionPerformed(evt);
            }
        });

        btnEliminarVida.setText("Eliminar Vida");
        btnEliminarVida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVidaActionPerformed(evt);
            }
        });

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Nombre Asegurado :");

        txtNombreAsegurado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAseguradoActionPerformed(evt);
            }
        });

        txtEdadAsegurado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadAseguradoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Edad Asegurado");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Valor Seguro Vida:");

        txtValorFallecimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorFallecimientoActionPerformed(evt);
            }
        });

        cblSeleccionSeguro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Vida", "Automotriz" }));
        cblSeleccionSeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cblSeleccionSeguroActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Tipo Seguro:");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnEliminarAutomotriz.setText("Eliminar Automotriz");
        btnEliminarAutomotriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAutomotrizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cblSeleccionSeguro, 0, 127, Short.MAX_VALUE)
                            .addComponent(txtFechaVigencia)
                            .addComponent(txtCosto)
                            .addComponent(txtNombreCliente)
                            .addComponent(txtIdentificador))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarVida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarAutomotriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAvaluoFiscal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDeducible, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                        .addComponent(txtPatente)))
                                .addGap(112, 112, 112)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreAsegurado, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEdadAsegurado, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtValorFallecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(36, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnListar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarVida)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarAutomotriz))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtFechaVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cblSeleccionSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDeducible)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNombreAsegurado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtEdadAsegurado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtValorFallecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAvaluoFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(28, 28, 28))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pagos"));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Identificador :");

        txtIngresoIDPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngresoIDPagarActionPerformed(evt);
            }
        });

        btnPagarSeguroVida.setText("Pagar Seguro Vida");
        btnPagarSeguroVida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarSeguroVidaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("El monto a pagar por el seguro es :");

        txtMuestraPagoSeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMuestraPagoSeguroActionPerformed(evt);
            }
        });

        btnPagarSeguroAuto.setText("Pagar Seguro Automotriz");
        btnPagarSeguroAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarSeguroAutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPagarSeguroAuto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPagarSeguroVida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIngresoIDPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMuestraPagoSeguro))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(txtIngresoIDPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPagarSeguroVida)
                .addGap(18, 18, 18)
                .addComponent(btnPagarSeguroAuto)
                .addGap(59, 59, 59)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(txtMuestraPagoSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("");
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdentificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificadorActionPerformed


    }//GEN-LAST:event_txtIdentificadorActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        Listar list = new Listar();
        list.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:

// TODO add your handling code here:System.out.println(cblSeleccionSeguro.getSelectedItem().toString());
        if (cblSeleccionSeguro.getSelectedItem().toString().equals("Vida")) {
            System.out.println("Se guardara Seguro Vida");

            Vida v = new Vida();
            v.setIdentificador(Integer.parseInt(txtIdentificador.getText()));
            v.setNombreCliente(txtNombreCliente.getText());
            v.setCosto(Integer.parseInt(txtCosto.getText()));
            v.setFechaVigencia(Integer.parseInt(txtFechaVigencia.getText()));
            v.setNombreAsegurado(txtNombreAsegurado.getText());
            v.setEdadAsegurado(Integer.parseInt(txtEdadAsegurado.getText()));
            v.setValorFallecimiento(Integer.parseInt(txtValorFallecimiento.getText()));

            boolean resultado = false;
            resultado = ControlVida.crearVida(v);

            if (resultado) {
                txtIdentificador.setText("");
                txtNombreCliente.setText("");
                txtCosto.setText("");
                txtFechaVigencia.setText("");
                txtNombreAsegurado.setText("");
                txtEdadAsegurado.setText("");
                txtValorFallecimiento.setText("");

            } else {
                txtIdentificador.setText("Error");
                txtNombreCliente.setText("Error");
                txtCosto.setText("Error");
                txtFechaVigencia.setText("Error");
                txtNombreAsegurado.setText("Error");
                txtEdadAsegurado.setText("Error");
                txtValorFallecimiento.setText("Error");
            }

        } else {
        }
        {
            if (cblSeleccionSeguro.getSelectedItem().toString().equals("Automotriz")) {
                System.out.println("Se guardara Seguro Automotriz");

                Automotriz a = new Automotriz();
                ///Vehiculo vehic = new Vehiculo();
                a.setIdentificador(Integer.parseInt(txtIdentificador.getText()));
                a.setNombreCliente(txtNombreCliente.getText());
                a.setCosto(Integer.parseInt(txtCosto.getText()));
                a.setFechaVigencia(Integer.parseInt(txtFechaVigencia.getText()));
                a.setDeducibleUf(Integer.parseInt(txtDeducible.getText()));
                a.vehiculo.setPatente(txtPatente.getText());
                a.vehiculo.setMarca(txtMarca.getText());
                a.vehiculo.setAvaluoFiscal(Integer.parseInt(txtAvaluoFiscal.getText()));

                boolean resultado = false;
                resultado = ControlAutomotriz.crearAutomotriz(a);

                if (resultado) {
                    txtIdentificador.setText("");
                    txtNombreCliente.setText("");
                    txtCosto.setText("");
                    txtFechaVigencia.setText("");
                    txtDeducible.setText("");
                    txtPatente.setText("");
                    txtMarca.setText("");
                    txtAvaluoFiscal.setText("");

                } else {
                    txtIdentificador.setText("Error");
                    txtNombreCliente.setText("Error");;
                    txtCosto.setText("Error");;
                    txtFechaVigencia.setText("Error");;
                    txtDeducible.setText("Error");;
                    txtPatente.setText("Error");;
                    txtMarca.setText("Error");;
                    txtAvaluoFiscal.setText("Error");;
                }

            } else {
                if (cblSeleccionSeguro.getSelectedItem().toString().equals("Seleccionar")) {
                    System.out.println("Haga la selección de tipo seguro");

                } else {
                }
            }

            // TODO add your handling code here:
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtEdadAseguradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadAseguradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadAseguradoActionPerformed

    private void txtNombreAseguradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAseguradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAseguradoActionPerformed

    private void txtIngresoIDPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngresoIDPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngresoIDPagarActionPerformed

    private void txtValorFallecimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorFallecimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorFallecimientoActionPerformed

    private void cblSeleccionSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cblSeleccionSeguroActionPerformed

// TODO add your handling code here:System.out.println(cblSeleccionSeguro.getSelectedItem().toString());
        if (cblSeleccionSeguro.getSelectedItem().toString().equals("Vida")) {
            System.out.println("Selecciono VIDA");
            txtDeducible.setEnabled(false);
            txtPatente.setEnabled(false);
            txtMarca.setEnabled(false);
            txtAvaluoFiscal.setEnabled(false);
            txtNombreAsegurado.setEnabled(true);
            txtEdadAsegurado.setEnabled(true);
            txtValorFallecimiento.setEnabled(true);

        } else {
        }
        {
            if (cblSeleccionSeguro.getSelectedItem().toString().equals("Automotriz")) {
                System.out.println("Selecciono Automotriz");
                txtPatente.setEnabled(true);
                txtDeducible.setEnabled(true);
                txtMarca.setEnabled(true);
                txtAvaluoFiscal.setEnabled(true);
                txtNombreAsegurado.setEnabled(false);
                txtEdadAsegurado.setEnabled(false);
                txtValorFallecimiento.setEnabled(false);

            } else {
                if (cblSeleccionSeguro.getSelectedItem().toString().equals("Seleccionar")) {
                    System.out.println("Sin Seleccionar");
                    txtPatente.setEnabled(false);
                    txtDeducible.setEnabled(false);
                    txtMarca.setEnabled(false);
                    txtAvaluoFiscal.setEnabled(false);
                    txtNombreAsegurado.setEnabled(false);
                    txtEdadAsegurado.setEnabled(false);
                    txtValorFallecimiento.setEnabled(false);
                } else {
                }
            }

            // TODO add your handling code here:
        }

    }//GEN-LAST:event_cblSeleccionSeguroActionPerformed

    private void txtDeducibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeducibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeducibleActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
  
    private void btnEliminarVidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVidaActionPerformed
        Vida vida22 = new Vida();
        vida22.setIdentificador(Integer.parseInt(txtIdentificador.getText()));
       // vida22.setNombreCliente(txtNombreCliente.getText());
        //vida22.setCosto(Integer.parseInt(txtCosto.getText()));
        //vida22.setFechaVigencia(Integer.parseInt(txtFechaVigencia.getText()));
        //vida22.setNombreAsegurado(txtNombreAsegurado.getText());
        //vida22.setEdadAsegurado(Integer.parseInt(txtEdadAsegurado.getText()));
        //vida22.setValorFallecimiento(Integer.parseInt(txtValorFallecimiento.getText()));

        boolean res = false;
        res = ControlVida.borrarSeguroVida(vida22);
        if (res) {
            JOptionPane.showMessageDialog(this, "Hecho con EXITO!!!", "ELIMINAR", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "SE ENCONTRO UN ERRROR", "ELIMINAR", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btnEliminarVidaActionPerformed

    private void btnPagarSeguroVidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarSeguroVidaActionPerformed

        //toma los datos de las cajas de texto....
        Vida vida33 = new Vida();
        vida33.setIdentificador(Integer.parseInt(txtIngresoIDPagar.getText()));
        

        //llamar a la capa de control
        ///recuperar el resultado de la eliminación.
        double resu = 0;
        double pagoTotalSeguroVida = 0;
        
        resu = vida33.pagoSeguro();
       
        txtMuestraPagoSeguro.setText(pagoTotalSeguroVida+"");
                
    }//GEN-LAST:event_btnPagarSeguroVidaActionPerformed

    private void btnEliminarAutomotrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAutomotrizActionPerformed
        Automotriz auto22 = new Automotriz();
        auto22.setIdentificador(Integer.parseInt(txtIdentificador.getText()));
        //auto22.setNombreCliente(txtNombreCliente.getText());
        ///auto22.setCosto(Integer.parseInt(txtCosto.getText()));
        //auto22.setFechaVigencia(Integer.parseInt(txtFechaVigencia.getText()));
        //auto22.setDeducibleUf(Integer.parseInt(txtDeducible.getText()));
        //auto22.vehiculo.setPatente(txtPatente.getText());
        //auto22.vehiculo.setMarca(txtMarca.getText());
        //auto22.vehiculo.setAvaluoFiscal(Integer.parseInt(txtAvaluoFiscal.getText()));

        boolean ress = false;
        ress = ControlAutomotriz.borrarSeguroAutomotriz(auto22);
        if (ress) {
            JOptionPane.showMessageDialog(this, "Eliminado Con Exito", "Funcion Eliminar", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Eliminado Con Exito", "Funcion Eliminar", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnEliminarAutomotrizActionPerformed

    private void btnPagarSeguroAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarSeguroAutoActionPerformed
       
        //toma los datos de las cajas de texto....
        Automotriz autm = new Automotriz();
        autm.setIdentificador(Integer.parseInt(txtIngresoIDPagar.getText()));
        

        //llamar a la capa de control
        ///recuperar el resultado de la eliminación.
        double resuaut = 0;
        double pagoPerdidaTotal = 0;
        
        resuaut = autm.pagoSeguro();
        txtMuestraPagoSeguro.setText(pagoPerdidaTotal+"");
        
    }//GEN-LAST:event_btnPagarSeguroAutoActionPerformed

    private void txtMuestraPagoSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMuestraPagoSeguroActionPerformed
        
    }//GEN-LAST:event_txtMuestraPagoSeguroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUnico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarAutomotriz;
    private javax.swing.JButton btnEliminarVida;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnPagarSeguroAuto;
    private javax.swing.JButton btnPagarSeguroVida;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cblSeleccionSeguro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtAvaluoFiscal;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtDeducible;
    private javax.swing.JTextField txtEdadAsegurado;
    private javax.swing.JTextField txtFechaVigencia;
    private javax.swing.JTextField txtIdentificador;
    private javax.swing.JTextField txtIngresoIDPagar;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMuestraPagoSeguro;
    private javax.swing.JTextField txtNombreAsegurado;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtPatente;
    private javax.swing.JTextField txtValorFallecimiento;
    // End of variables declaration//GEN-END:variables
}
//CODIGO CREADO POR KAREN LUENGO TORO Y VICTOR BASTIAS ESCOBAR